// Generated by CoffeeScript 1.3.3
(function() {

  this.title = 'Swyp Web Client';

  this.stylesheets = ['/style'];

  this.scripts = ['/socket.io/socket.io', '/zappa/jquery', '/zappa/zappa', '/swyp', '/ArraySetMath', '/d3.v2.min', '/force', '/jquery-1.7.2.min', '/swypUI', '/login', '/md5'];

  h1("#instructions", img("#preview", div('#account', function() {
    if (!this.token) {
      return a('#login_button', {
        href: '#'
      }, function() {
        return 'Login/Register';
      });
    } else {
      return a('#login_button', {
        href: '/logout'
      }, function() {
        return 'Logout';
      });
    }
  })));

  div('#debug', function() {
    div('swypStatusControls', function() {
      input({
        id: 'token_input',
        type: 'text',
        name: 'token_input',
        placeholder: 'session token',
        size: 50,
        value: this.token
      });
      return input({
        id: 'statusupdate_button',
        type: 'button',
        value: "status update!"
      });
    });
    div('swypOutControls', function() {
      input({
        id: 'recipient_input',
        type: 'text',
        name: 'recipient_input',
        placeholder: 'recipient publicID or empty for nearby',
        size: 50
      });
      return input({
        id: 'swypOut_button',
        type: 'button',
        value: "swyp out!"
      });
    });
    return div('#swypMessages', function() {});
  });

}).call(this);
